version: '3.7'
services:

  binary_classifier:
    image: backend-binary-classifier
    build: ./server
    restart: always
    environment:
      - DEVICE=cuda
      - MODEL_NAME=/home/backend/bert_model
      - BACKEND_TYPE=binary_classifier

      - BATCH_SIZE=32

      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
    volumes:
      - ./bert_model:/home/backend/bert_model
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    networks:
      - binary_classifier_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]


  nginx_binary_classifier:
    build: ./proxy/binary
    ports:
      - "8081:8081"
    restart: always
    networks:
      - binary_classifier_network
      - main_network
    depends_on:
      - binary_classifier

  binary_classifier_triton:
    image: backend-binary-classifier_triton
    build: ./server_triton
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]


  bart_summarizer:
    build: ./server
    container_name: backend-bart-summarizer
    restart: always
    environment:
      - DEVICE=cpu
      - MODEL_NAME=/home/backend/bart_model
      - BACKEND_TYPE=bart

      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
    volumes:
      - ./bart_model:/home/backend/bart_model
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - "8081:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  nginx_bart_summarizer:
    build: ./proxy/summarizer
    ports:
      - "8082:8082"
    restart: always
    networks:
      - summarizer_network
      - main_network
    depends_on:
      - bart_summarizer


  backend_gui:
    build: ./gui
    image: backend-gui
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production

      - BINARY_CLASSIFIER=nginx_binary_classifier:8081
      - BINARY_CLASSIFIER_TYPE=BASE
      - SUMMARIZER=nginx_bart_summarizer:8082
    restart: always
    networks:
      - main_network
    ports:
      - "8080:5000"


networks:
  binary_classifier_network:
    driver: bridge
  summarizer_network:
    driver: bridge
  main_network: {}